### ISSUE TITLE
CSON.writeFile writing json by default

### ISSUE THREAD

**Issue by charlierudolph** [atom/season#13]
CSON.writeFile only writes cson if the file extension ends with `.cson` and write json otherwise.
I'd prefer it to be the other way around and that is only writes json when the file extension is `.json` and cson otherwise. 

This is a cson library so I think that makes sense. I like the idea of writing being able to convert json to cson (to make it easier for users to convert over) but otherwise don't see any reason to have all this support for json.

**Comment by kevinsawicki** [comment]
> This is a cson library so I think that makes sense.

Yeah, I agree.

> all this support for json.

The main reason here is this library is used in Atom where there is a heavy mix of JSON and CSON files and this was library was meant to be able to read/write either transparently in a single API.
