### ISSUE TITLE
Add feature to write all keys as strings

### ISSUE THREAD

**Issue by silvenon** [atom/season#7]
`file.json`:
```json
{
  "a": 5,
  "b": 6,
  "c-d": 7
}
```
`index.js`:
```js
var CSON = require('season');
CSON.writeFileSync('file.cson', CSON.readFileSync('file.json'));
```
`file.cson`:
```cson
a: 5
b: 6
"c-d": 7
```

I would prefer to have all keys written as strings, it makes bigger files much easier to read.

**Comment by kevinsawicki** [comment]
This library now just uses https://github.com/groupon/cson-parser for stringifying, would you mind opening an issue there to request this feature?

Then this library will upgrade to that version once it is added.
